name = "herza"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.168.146.169"
UUID = "9664bcd8-d935-4ec4-b307-e3461dad804d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
