name = "haka"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "211.230.110.231:50008"
UUID = "bbd40e74-f967-4f0e-aabe-ebc89618cf5e"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
