name = "vlesscfku"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "206.237.98.76"
UUID = "7ea0c91b-2ccd-4fae-8c73-615496f11a38"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
