name = "hakaidok"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.110.91.198"
UUID = "c8975ae2-bcc2-44fc-9609-41e160b063db"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
